language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: Exy5I1gr/RxBS0C7WE6HHB/ZfRMJLeX5g29s9LWQv8QxNhbg03fvFVIy3Sj+oKDsgszmkuDM2+fG55E1vxw0NA1torsqypInRkAlg7RBYj4TVDE9Vk7K1NXGShy8ea8QsF2wMpsCPZQ6iLQFu2VfFLGruvv/cM9QnEZhXOuiPj7lXM4TnPA3vv6l4xwjci7z0Ih967obKGwz4GHlUnIM+snnVjuH4f0PT3p6qgJF0a/sHbV5DeFCctXK0UAv+R4dwkb577eHjEfljlMaEbfOaGifyU0iZ/WPUIgPCbCdsSJ6S4XLHTXHi4EHX0UKy82Q7+W4V9Jo1x0E0huJNv5wjEnKQBw1kGEA6b+Hvc1tekIG+ccu5Uv7mzsi9f26JdEVJ6F2KEuPpNZ5NBsQmyGzRBinAXs8TEWqRJttm3FX5iUbqFfshJKLZlgiqLd5NyHwO4JxqN+ZUUVDh2g2BqSPqvPWIkEdszQrhT8mfCd+bTk2NQqhzoObwx1eyLVuQ68nHkAOYEzxEwWv7C7Dc5+CLjWRHE2ZZHUv+58CIL0GleLMKI3v9erLmHwga54m1/Qa6EyQ/KbAMaiX6LKcYi/WrVNUpJ1RmlRF0rSZUazvmIhmP4jrT1gwoxHGYkYKJ6KspjymEGfgqN4IDva7X5/nSjIylq2MFTmsB0/SirhfAdw=
  app: startcomm
  on:
    repo: konagayoshi/startup_community
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database startup_community_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - rake db:reset RAILS_ENV=test